"""first commit

Revision ID: 0995a36fb42b
Revises: 
Create Date: 2023-06-16 01:29:39.079338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0995a36fb42b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_form_user_data',
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=40), nullable=False),
    sa.Column('filled_form_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_form_user_data')
    # ### end Alembic commands ###
